# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QTreeWidget, QTreeWidgetItem, QDockWidget
from PyQt5.QtGui import QStandardItem

from canvas import Canvas
from dialogs import InputPointDialog, SetPointDialog

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowTitle("GIS tool")
        self.resize(1600, 1200)
        self.centralwidget = Canvas()
        self.dialogSetPoint = SetPointDialog(self.centralwidget)
        self.dialogInputPoint = InputPointDialog(self.centralwidget)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menuPoint = QtWidgets.QMenu('点操作', self.menubar)
        self.menuLine = QtWidgets.QMenu('线操作', self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.setStatusBar(self.statusbar)
        self.actionAddPoint = QtWidgets.QAction('增加点', self)
        self.actionDeletePoint = QtWidgets.QAction('删除点', self)
        self.actionInputPoint = QtWidgets.QAction('输入点', self)
        self.actionSelectPoint = QtWidgets.QAction('选择点', self)
        self.actionSetPoint = QtWidgets.QAction('设置点属性', self)
        self.actionAddLine = QtWidgets.QAction('增加线', self)
        self.actionDeleteLine = QtWidgets.QAction('删除线', self)
        self.menuPoint.addAction(self.actionAddPoint)
        self.menuPoint.addAction(self.actionDeletePoint)
        self.menuPoint.addAction(self.actionInputPoint)
        self.menuPoint.addAction(self.actionSelectPoint)
        self.menuPoint.addAction(self.actionSetPoint)
        self.menuLine.addAction(self.actionAddLine)
        self.menuLine.addAction(self.actionDeleteLine)
        self.menubar.addAction(self.menuPoint.menuAction())
        self.menubar.addAction(self.menuLine.menuAction())
        self.setMenuBar(self.menubar)

        self.dockItem = QDockWidget(self)
        self.tree = QTreeWidget(self)
        self.tree.setColumnCount(1)
        self.tree.setHeaderLabel('工程文件')
        rootPoint = QTreeWidgetItem(self.tree)
        rootPoint.setText(0, '点文件')
        rootLine = QTreeWidgetItem(self.tree)
        rootLine.setText(0, '线文件')
        rootRegion = QTreeWidgetItem(self.tree)
        rootRegion.setText(0, '面文件')
        self.tree.addTopLevelItems([rootPoint, rootLine, rootRegion])
        self.tree.move(100, 200)
        self.tree.expandAll()
        self.dockItem.setWidget(self.tree)
        self.addDockWidget(QtCore.Qt.LeftDockWidgetArea, self.dockItem)


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    window = Ui_MainWindow()

    window.show()
    sys.exit(app.exec_())
